### ISSUE TITLE
Handling empty inputs

### ISSUE THREAD

**Issue by ameentalahmeh** [fack2/Dictionary-Giphy-App#19]
You should be handling the `empty input` that can be by an ignorant user.
one of the simple ways (`alert`) through :

* Add if statement that checks if **input value** if not equal ' '  before your `fetch`

``
if (input !== ' ')
{ Here: Do your code } 
else
  {Here: Do alert that tells the user the input is empty }
``
--------------------------------
See the error response on below pic:
![Screenshot from 2019-07-04 09-33-55](https://user-images.githubusercontent.com/26909309/60644518-0f664680-9e3f-11e9-8e46-ea947aa7f513.png)

**Comment by sulieman1** [comment]
issue fixed!
you can now see a message if you leave the input field empty
@ameentalahmeh

**Comment by ameentalahmeh** [comment]
Great work **Dictionary-Giphy-App** :+1:
