### ISSUE TITLE
delete unneccessary comments and console.logs

### ISSUE THREAD

**Issue by eadehemingway** [fack2/Dictionary-Giphy-App#26]
https://github.com/fack2/Dictionary-Giphy-App/blob/39e6b5004a4a7c48fe14c52a59feb453b8f3c4fa/public/js/dom.js#L55-L68

this is the sort of thing that is usually caught in code reviews (at my work, a pull request wouldnt be merged if it had a console.log in it or had big bits of code commented out)

**Comment by sulieman1** [comment]
comments deleted!
@eadehemingway

**Comment by eadehemingway** [comment]
👍
