### ISSUE TITLE
no more for loops!

### ISSUE THREAD

**Issue by eadehemingway** [fack2/Dictionary-Giphy-App#27]
https://github.com/fack2/Dictionary-Giphy-App/blob/39e6b5004a4a7c48fe14c52a59feb453b8f3c4fa/public/js/dom.js#L40

replace this with forEach!

**Comment by sulieman1** [comment]
Replaced the for loop with a forEach method!
issue fixed
@eadehemingway

**Comment by eadehemingway** [comment]
very nice!
